# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_call:
    inputs:
      github_repository:
        description: 'The ${{ github.repository }}`
        required: true
      github_workspace:
        description: 'The ${{ github.workspace }}`
        required: true
    secrets:
      github_token:
        description: 'The GITHUB_TOKEN.'
        required: true

jobs:
  Release:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create the release
        uses: xmidt-org/release-builder-action@v2
        with:
          gh-repository: ${{ inputs.github_repository }}
          gh-workspace: ${{ inputs.github_workspace }}
          gh-token: ${{ secrets.github_token }}

      - name: Upload the Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.prep.outputs.rname }}
          draft: false
          prerelease: false
          bodyFile: ${{ steps.prep.outputs.body }}
          artifacts: "artifacts/*"
          token: ${{ secrets.github_token }}
